experiment: "my_experiment"
outdir: "/path/to/output"
kernel_name: "python3-odiv-stable"
start_year: 1993
end_year: 2017
#exclude:
#  - "notebook1.ipynb"
#  - "notebook2.ipynb"
only:
  - "AAIW_PV.ipynb"
  - "ArcticMeanTempSalinity.ipynb"
  - "Bottom_property_bias_WOA18.ipynb"
  - "Drake_Transport.ipynb"
  - "ENSO_variability.ipynb"
  - "Global_Meridional_Overturning.ipynb"
  - "Med_Outflow.ipynb"
  - "Mixed_Layer_Depths.ipynb"
  - "Northward_Heat_Transport.ipynb"
  - "Ocean_heat_content.ipynb"
  - "Overturning_zrho.ipynb"
  - "SO_Ross_AB_ice_thetao.ipynb"
  - "SOshelf_bottom_salinity.ipynb"
  - "ssh_wbc.ipynb"
  - "SST_bias_NOAA_OISSTv2.ipynb"
  - "Tidal_Energy_Conversion_Deep.ipynb"
  - "Ventilation.ipynb"
  - "WMT_North_Atlantic.ipynb"
  - "WOA13_yz_bias.ipynb"
  - "WOA18_yz_bias.ipynb"
notebooks:
  notebook3.ipynb:
    some_setting: "value1"
    another_setting: "value2"
    experiment: "notebook3_experiment"
    start_year: 2020
  notebook4.ipynb:
    some_setting: "value3"
    another_setting: "value4"
    experiment: "notebook4_experiment"
    end_year: 2025

